Botun paylaştığı duyuruyu spamlamasını engellemek
acikkaynak/discord-it-yardim-bot pull request #48
Opened 2023-02-17 21:55 UTC by lburaq

Son 50 mesajın içerisinde botun paylaştığı duyuru varsa mesaj göndermeyecektir.

**NOT:** find methodunda `msg.author.bot` komutu da çalışıyor fakat `/pin` kullanıldığında botun mesajı olarak varsaydığı için gene mesaj göndermeyeceğinden `msg.content == ''` kullanılmıştır.

2023-02-19 04:00 UTC, bilinenkisi commented
#50 PR ile aynı değişikliklere sahip olduğu için ve diğer PR'dan önce açıldığı için bu PR'ın kapatılıp #50 PR ile devam edilmesi gerektiğini düşünmekteyim. @ramazansancar

2023-02-19 15:22 UTC, bilinenkisi approved these changes

2023-02-19 15:23 UTC, bilinenkisi commented on commands/sescek.js
> +        user.voice.setChannel(self.voice.channel).then(user=>{
@lburaq Buradaki then-catch yapısını test etme şansın oldu mu?

2023-02-19 15:24 UTC, lburaq commented on commands/sescek.js
> +        user.voice.setChannel(self.voice.channel).then(user=>{
Evet test ettim, sorunsuz bir şekilde çalışıyor.

2023-02-19 15:26 UTC, bilinenkisi requested changes

2023-02-19 15:26 UTC, bilinenkisi commented on events/ready.js
> +        if(!messages.find(msg=> msg.content == '')){
Burada mesaj içeriği yerine yollanan mesaj'ın idsi oldMessageId tarzında bir değişkene sürekli kayıt edilmesi ve bu id'nin son 50 mesaj içerisinde olup olmadığına bakılması daha efektif olacaktır.

2023-02-19 15:26 UTC, bilinenkisi commented on events/ready.js
> +        if(!messages.find(msg=> msg.content == '')){
Hatta hem gece hem de gündüz interval'ları aynı oldMessageId değişkenini kullanabilir.

2023-02-19 15:27 UTC, bilinenkisi commented on commands/sescek.js
> +        user.voice.setChannel(self.voice.channel).then(user=>{
Tamamdır o zaman

2023-02-19 19:44 UTC, lburaq commented on events/ready.js
> +        if(!messages.find(msg=> msg.content == '')){
Söylediğiniz mantıklı geldi bu yüzden gönderilen mesajı oldMessage değişkenine sürekli kayıt ediyor ve son 50 mesajın oldMessage ile aynı olup olmadığına bakıyor.

2023-02-20 11:41 UTC, bilinenkisi approved these changes

2023-02-20 16:08 UTC, abtonc commented
we will continue with #50, thanks @bilinenkisi and @lburaq

2023-02-20 16:08 UTC, closed without merging